---
title: "marine-genomics - Workshop 4"
output: html_document
date: "2026-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Setup

Create a new github repository called marine-genomics.
Create a project that is linked to github repository
Create RMarkdown document

## Assembly

Step 1. Create a working directory called flye and then make a symbolic link to the bbd read data

```bash
mkdir flye
ln -s /pvol/data/metagenome_assembly/bbd_0.1.fastq.gz .
```

Step 2. Make a shell script called run_flye_bbd.sh and include the following

```
#!/bin/bash
#SBATCH --time=720
#SBATCH --ntasks=12 --mem=10gb

echo "Starting flye bbd in $(pwd) at $(date)"

flye --nano-hq ../bbd_0.1.fastq.gz --threads 12 --out-dir bbd --meta

echo "Finished flye bbd in $(pwd) at $(date)"
```

Step 3. Submit run_flye_bbd.sh using sbatch

```bash
sbatch run_flye_bbd.sh
```

## Binning with metabat

Step 1. Create directory called metabat

```bash
mkdir metabat
cd metabat
```

Step 2. Extract depth information
```bash
cat ../flye/bbd/assembly_info.txt  | grep -v '#' | awk '{OFS="\t";print $1,$3}' > depths_bbd.txt
```

Step 3. Reorder contigs based on depth
```bash
cat depths_bbd.txt | awk '{print $1}' | xargs samtools faidx ../flye/bbd/assembly.fasta > assembly_bbd_ordered.fasta
```

Step 4. Run metabat
```bash
metabat2 -i assembly_bbd_ordered.fasta -a depths_bbd.txt --cvExt -o bins_bbd/metabat --seed 5
```

## Check bin quality with checkm

Step 1. Create directory called checkm

```bash
mkdir checkm
cd checkm
```

Step 2. Find the number of the largest contiguous in the bbd assembly (will need to manually add this contig because it usually isn't included in the bins from metabat)

```bash
cat ../flye/bbd/assembly.fasta | bioawk -c fastx '{print length($seq),$name}' | sort -n
```
contig 128 is the largest

Step 3. Create directory called bins_bbd and copy bins_bbd from metabat

```bash
mkdir bins_bbd
cp ../metabat/bins_bbd/*.fa bins_bbd/
samtools faidx ../flye/bbd/assembly.fasta contig_128 > bins_bbd/contig_128.fa
```

Step 4. Create a slurm script for checkm called run_checkm_bbd.sh in the checkm directory

```
#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=6 --mem=40gb

echo "Starting checkm in $(pwd) at $(date)"

shopt -s expand_aliases
alias checkm='apptainer run -B /pvol/:/pvol /pvol/data/sif/checkm.sif checkm'

checkm lineage_wf bins_bbd out -t 4 -x fa -f checkm_results_bbd.txt

echo "Finished checkm in $(pwd) at $(date)"
```
Troubleshooting insight: Had to change memory from 10gb to 40gb due to the server being overloaded

Step 5. Submit run_checkm_bbd.sh using sbatch

```bash
sbatch run_checkm_bbd.sh
```

## Select bins based on checkm results

Step 1. Look at results from checkm analysis using head
```bash
head checkm_results_bbd.txt 
```

Step 2. Show a few more lines using head -n 20 
```bash
head -n 20 checkm_results_bbd.txt
```

Step 3. Use checkm completeness greater than 15% using awk to extract the bin IDs
```bash
cat checkm_results_bbd.txt | awk '$13>15'
```

Step 4. Change it from the entire line to just the bin ID using the print command
```bash
cat checkm_results_bbd.txt | awk '$13>15{print $1}'
```

Step 5. Send output to a file so it can be used in other steps
```bash
cat checkm_results_bbd.txt | awk '$13>15{print $1}' > bbd_topbins.txt
```

## Perform taxonomic classification with gtdbtk

Step 1. Create working directory called gtdbtk
```bash
mkdir gtdbtk
cd gtdbtk
```

Step 2. Create a subfolder within gtdbtk called genomes (this is where a copy of each of the top bins will go)
```bash
mkdir genomes
```

Step 3. Build the command and get the loop working
```bash
while read bin;do echo $bin;done < ../checkm/bbd_topbins.txt
```

Step 4. Use echo to print the name of the bins. Turn the bin name into a path specifying the fasta file for the bin. 
Every bin will need to prepend the path to its folder ../metabat/bins_bbd/ and then append the file extension .fa
```bash
while read bin;do echo "../metabat/bins_bbd/${bin}.fa";done < ../checkm/bbd_topbins.txt
```

Step 5. Perform the copy from checkm to metabat
```bash
while read bin;do cp "../metabat/bins_bbd/${bin}.fa" genomes;done < ../checkm/bbd_topbins.txt
```
Troubleshooting insight: Had an error that said contig_128 not found. Had to copy contig_128 from checkm to metabat

Step 6. Check that it worked correctly by listing files within the genomes directory (should see one file for each of the bins)
```bash
ls genomes
```

Step 7. Create slurm script in the gtdbtk directory called run_gtdbtk.sh
```
#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=2 --mem=40gb

echo "Starting gtdbtk in $(pwd) at $(date)"

shopt -s expand_aliases
alias gtdbtk='apptainer run -B /pvol:/pvol,/pvol/data/mg/gtdbtkdata/release207_v2/:/refdata /pvol/data/sif/gtdbtk.sif'

gtdbtk classify_wf -x fa --cpus 2 --genome_dir genomes --out_dir out --skip_ani_screen

echo "Finished gtdbtk in $(pwd) at $(date)"
```
Troubleshooting insight: Had to change memory from 24gb to 40gb due to the server being overloaded

Step 8. Submit run_gtdbtk.sh using sbatch
```bash
sbatch run_gtdbtk.sh
```

## Find and annotate genes with prokka

Step 1. Create directory called prokka
```bash
mkdir prokka
cd prokka
```

Step 2. Find the first bin ID 
```bash
head -n 1 ../checkm/bbd_topbins.txt
```
First bin ID is contig_128

Step 3. Run prokka on a single bin (bin = contig_128) and create folder called contig_128
```bash
bin=contig_128
prokka--outdir $bin --prefix $bin  ../metabat/bins_bbd/${bin}.fa
```

Step 4. check the contents of folder called contig_128
```bash
ls contig_128
```
Contents:
contig_128.err  contig_128.ffn  contig_128.fsa  contig_128.gff  contig_128.sqn  contig_128.tsv
contig_128.faa  contig_128.fna  contig_128.gbk  contig_128.log  contig_128.tbl  contig_128.txt

Step 5. Run prokka on all the metagenomes using a slurm script called run_prokka.sh
```
#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=2 --mem=2gb

echo "Starting prokka in $(pwd) at $(date)"

shopt -s expand_aliases
alias prokka='apptainer run -B /pvol/:/pvol /pvol/data/sif/prokka.sif prokka'

while read bin;do 
  prokka --outdir $bin --prefix $bin "../metabat/bins_bbd/${bin}.fa";
done < ../checkm/bbd_topbins.txt

echo "Finished prokka in $(pwd) at $(date)"
```

Step 6. Submit run_prokka.sh using sbatch
```bash
sbatch run_prokka.sh
```

## Infer metabolic pathways

Step 1. Create a directoy for minpath results
```bash
mkdir minpath
cd minpath
```

Step 2. Look for the .tsv file for a single bin
```bash
head ../prokka/metabat.5/metabat.5.tsv
```

Step 3. Change minpath to keep a unique ID for each gene (column 1) and its EC number (column 5) using awk
```bash
head ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '{print $1,$5}'
```

Step 4. Filter the output to only include lines with an EC number
```bash
head ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{print $1,$5}'
```

Step 5. Ensure the output is tab separated and remove the header line
```bash
head ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

Step 6. Change head to cat to chnage from the first 10 lines to all of the genes
```bash
cat ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

Step 7. Send the output to a file so that it can be used as input to minpath
```bash
cat ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus' > metabat.5.ec
```

Step 8. Run minpath on the file
```bash
minpath -ec metabat.5.ec -report metabat.5.ec.report -details metabat.5.ec.details
```

Step 9. Look at the top few lines of output
```bash
head metabat.5.ec.report 
```

path PWY-5143 any n/a  naive 1  minpath 1  fam0  1  fam-found  1  name  long-chain fatty acid activation
path PWY-5083 any n/a  naive 1  minpath 1  fam0  3  fam-found  1  name  NAD(P)/NADPH interconversion
path PWY-8138 any n/a  naive 1  minpath 1  fam0  1  fam-found  1  name  polyphosphate metabolism
path PWY-6559 any n/a  naive 1  minpath 1  fam0  2  fam-found  1  name  spermidine biosynthesis II
path PWY-6562 any n/a  naive 1  minpath 1  fam0  4  fam-found  2  name  norspermidine biosynthesis
path PWY-6565 any n/a  naive 1  minpath 1  fam0  5  fam-found  2  name  superpathway of polyamine biosynthesis III
path PWY-8072 any n/a  naive 1  minpath 1  fam0  1  fam-found  1  name  alanine racemization
path COMPLETE-ARO-PWY any n/a  naive 1  minpath 0  fam0  18  fam-found  1  name  superpathway of aromatic amino acid biosynthesis
path P4-PWY any n/a  naive 1  minpath 1  fam0  17  fam-found  1  name  superpathway of L-lysine, L-threonine and L-methionine biosynthesis I
path PWY-724 any n/a  naive 1  minpath 0  fam0  7  fam-found  1  name  superpathway of L-lysine, L-threonine and L-methionine biosynthesis II

Step 10. Prepare minpath inputs for bin
```bash
while read bin;do 
  cat ../prokka/$bin/${bin}.tsv | awk -F '\t' '$5{printf("%s\t%s\n", $1,$5)}' | grep -v '^locus' > ${bin}.ec 
done < ../checkm/bbd_topbins.txt
```

Step 11. Run minpath on every bin
```bash
while read bin;do 
  minpath -ec ${bin}.ec -report ${bin}.ec.report -details ${bin}.ec.details
done < ../checkm/bbd_topbins.txt
```

Step 12. Search for this pathway across all the bins
```bash
grep 'PWY-101' *.ec.report
```

contig_128.ec.report:path PWY-101 any n/a  naive 1  minpath 0  fam0  4  fam-found  1  name  photosynthesis light reactions
metabat.33.ec.report:path PWY-101 any n/a  naive 1  minpath 0  fam0  4  fam-found  1  name  photosynthesis light reactions
metabat.37.ec.report:path PWY-101 any n/a  naive 1  minpath 1  fam0  4  fam-found  4  name  photosynthesis light reactions
metabat.46.ec.report:path PWY-101 any n/a  naive 1  minpath 1  fam0  4  fam-found  1  name  photosynthesis light reactions

There are four bins that contain at least one gene from the pathway PWY-101
Bin metabat.37 has all the genes and is a complete pathway

Step 13. Cross reference the results with the output from gtdbth to see the taxonomy of of bins containing the pathway (will need to change to use the correct bin numbers)
```bash
grep 'metabat.37' ../gtdbtk/out2/gtdbtk.bac120.summary.tsv
```
metabat.37      d__Bacteria;p__Cyanobacteria;c__Cyanobacteriia;o__Cyanobacteriales;f__Desertifilaceae;g__Roseofilum;s__Roseofilum reptotaenium_A    GCA_001890975.1 95.0    d__Bacteria;p__Cyanobacteria;c__Cyanobacteriia;o__Cyanobacteriales;f__Desertifilaceae;g__Roseofilum;s__Roseofilum reptotaenium_A    96.64   0.863   GCA_001890975.1 95.0    d__Bacteria;p__Cyanobacteria;c__Cyanobacteriia;o__Cyanobacteriales;f__Desertifilaceae;g__Roseofilum;s__Roseofilum reptotaenium_A    96.64   0.863   d__Bacteria;p__Cyanobacteria;c__Cyanobacteriia;o__Cyanobacteriales;f__Desertifilaceae;g__Roseofilum;s__     taxonomic classification defined by topology and ANI    topological placement and ANI have congruent species assignments    GCA_002340255.1, s__Roseofilum sp002340255, 95.0, 94.19, 0.87   89.99   11      N/A     N/A

```bash
grep 'metabat.33' ../gtdbtk/out2/gtdbtk.bac120.summary.tsv
```
metabat.33      d__Bacteria;p__Desulfobacterota;c__Desulfobacteria;o__Desulfobacterales;f__Desulforegulaceae;g__;s__    N/A     N/A     N/AN/A      N/A     N/A     N/A     N/A     N/A     N/A     d__Bacteria;p__Desulfobacterota;c__Desulfobacteria;o__Desulfobacterales;f__Desulforegulaceae;g__;s__        taxonomic novelty determined using RED  classification based on placement in class-level tree   N/A     16.08   11 0.8249   N/A

```bash
grep 'metabat.46' ../gtdbtk/out2/gtdbtk.bac120.summary.tsv
```
metabat.46      d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Vallitaleaceae;g__;s__   N/A     N/A     N/A     N/A     N/AN/A      N/A     N/A     N/A     N/A     d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Vallitaleaceae;g__;s__   taxonomic novelty determined using RED      classification based on placement in class-level tree   N/A     16.06   11      0.84647 N/A

```bash
grep 'contig_128' ../gtdbtk/out2/gtdbtk.bac120.summary.tsv
```
contig_128      d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Cytophagales;f__Bernardetiaceae;g__UBA2561;s__UBA2561 sp002340355 GCA_002340355.1     95.0    d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Cytophagales;f__Bernardetiaceae;g__UBA2561;s__UBA2561 sp002340355 98.71   0.966       GCA_002340355.1 95.0    d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Cytophagales;f__Bernardetiaceae;g__UBA2561;s__UBA2561 sp002340355     98.71   0.966   d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Cytophagales;f__Bernardetiaceae;g__;s__   taxonomic classification defined by topology and ANI        topological placement and ANI have congruent species assignments        N/A     90.91   11      N/A     N/A

Troubleshooting insight: Contig_128 not found in genomes so had to copy it from checkm and rerun gtdbtk slurm with contig_128 included (out2)

Step 14. Find out how many bins contain PWY-5360
```
grep 'PWY-5360' *.ec.report
```
metabat.42.ec.report:path PWY-5360 any n/a  naive 1  minpath 0  fam0  3  fam-found  1  name  superpathway of tetrathionate reduction (Salmonella typhimurium)

There is only one bin that contains the PWY-5360 and it is metabat.42

Step 15. Cross reference the results with the output from gtdbth to see the taxonomy of of bins containing the pathway (will need to change to use the correct bin numbers)
```bash
grep 'metabat.42' ../gtdbtk/out2/gtdbtk.bac120.summary.tsv
```
metabat.42      d__Bacteria;p__Campylobacterota;c__Campylobacteria;o__Campylobacterales;f__Arcobacteraceae;g__Halarcobacter;s__ N/A     N/AN/A      N/A     N/A     N/A     N/A     N/A     N/A     N/A     d__Bacteria;p__Campylobacterota;c__Campylobacteria;o__Campylobacterales;f__Arcobacteraceae;g__Halarcobacter;s__     ANI     classification based on placement in class-level tree   GCA_004116455.1, s__Halarcobacter sp004116455, 95.0, 81.38, 0.381; GCA_004118855.1, s__Halarcobacter sp004118855, 95.0, 80.71, 0.384; GCF_003346815.1, s__Halarcobacter bivalviorum, 95.0, 80.71, 0.406; GCA_001895145.1, s__Halarcobacter sp001895145, 95.0, 80.51, 0.403; GCF_005771535.1, s__Halarcobacter arenosus, 95.0, 80.5, 0.431; GCA_002869565.1, s__Halarcobacter sp002869565, 95.0, 80.37, 0.393; GCA_013373175.1, s__Halarcobacter sp013373175, 95.0, 80.3, 0.412; GCA_003252105.1, s__Halarcobacter sp003252105, 95.0, 79.87, 0.381; GCF_004116625.1, s__Halarcobacter mediterraneus, 95.0, 79.72, 0.374; GCF_013201825.1, s__Halarcobacter ebronensis, 95.0, 78.98, 0.343; GCF_006459125.1, s__Halarcobacter anaerophilus, 95.0, 78.79, 0.33 30.14       11      0.93462 N/A

The taxonomic family for metabat.42 is Arcobacteraceae


